### PR TITLE
18 info and examples

### PR DESCRIPTION
**Pull request by sroertgen**

### CODE REVIEW

**Comment by sroertgen** [comment]
@Phu2: Please deploy this branch to our test system

**Comment by Phu2** [comment]
Deployed [to ](https://reconcile-publish-test.skohub.io/)

**Comment by sroertgen** [comment]
@acka47 We now have some example service manifest urls to copy and a link to the overview page of all vocabularies.

**Comment by acka47** [comment]
This looks nice. One minor thing: Could you add a "copy to clipboard" icon to the buttons of the example vocabularies? Otherwise +1

**Comment by sroertgen** [comment]
@acka47 Icon added as well as a tooltip to indicate successfull copy.

**Comment by acka47** [comment]
> a tooltip to indicate successfull copy.

This is nice but it is shown – at least in my case – not near the mouse cursor bit many centimeters higher:

image

Could this be shown next to the mouse cursor position instead?

**Review by acka47 — APPROVED** [review]
Now everything works fine. Thanks! +1

**Pull request merged**
