### PR TITLE
19 account

### LINKED ISSUE #19: Offer alternatives for providing an account
Ideas:

- use GitHub or other authentication
- or ORCID

### PR DESCRIPTION
**Pull request by sroertgen**
This PR adds login options for providing an account using wikimedia or orcid oauth.

### CODE REVIEW

**Comment by sroertgen** [comment]
@Phu2 Please deploy to test system.

**Comment by Phu2** [comment]
Deployed to test.

**Comment by acka47** [comment]
Is this the latest status at https://reconcile-publish-test.skohub.io/?If yes, then the logos are missing, at least the Wikimedia one. I looged in with my Wikimedia account and it looks like this:

image

**Comment by sroertgen** [comment]
Tried reloading? They are there for me...

image

**Comment by sroertgen** [comment]
ah, you mean after the login. There is no logo currently shown. I will add one.

**Comment by sroertgen** [comment]
@Phu2 Please redeploy to test system.

**Comment by Phu2** [comment]
Deployed https://reconcile-publish-test.skohub.io/

**Comment by sroertgen** [comment]
@acka47 I implemented changes as requested. Please have a look at the login again

**Review by acka47 — APPROVED** [review]
+1 I could not test ORCID, though, as I do not have an account on the sandbox.

**Pull request merged**
